baseURL = "https://example.org/"
languageCode = "zh-CN"
title = "个人主页 - 即刻风格"
theme = "jike-style"

[params]
  name = "陈小明"
  bio = "产品设计师 | 摄影爱好者 | 旅行达人"
  avatar = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=200&q=80"
  author = "陈小明"
  following = 1200
  followers = 3500
  
  [[params.socials]]
    icon = "fab fa-weibo"
    url = "#"
  
  [[params.socials]]
    icon = "fab fa-weixin"
    url = "#"
  
  [[params.socials]]
    icon = "fab fa-github"
    url = "#"
  
  [[params.socials]]
    icon = "fab fa-instagram"
    url = "#"
  
  [params.topics]
    topics = ["产品设计", "用户体验", "摄影技巧", "旅行日记", "前端开发", "设计思维"]