baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'intro_page'
theme='neil-theme'

baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Jike Style Site"
theme = "jike-style"

[params]
  name = "陈小明"
  bio = "产品设计师 | 摄影爱好者 | 旅行达人"
  avatar = "/images/avatar.jpg"
  stats = [
    { value = 128, label = "动态" },
    { value = 1200, label = "关注" },
    { value = 3500, label = "粉丝" }
  ]
  socials = [
    { icon = "fab fa-weibo", url = "#" },
    { icon = "fab fa-weixin", url = "#" },
    { icon = "fab fa-github", url = "#" },
    { icon = "fab fa-instagram", url = "#" }
  ]

[[params.menu]]
  name = "动态"
  url = "/"
[[params.menu]]
  name = "文章"
  url = "/posts"
[[params.menu]]
  name = "照片"
  url = "/photos"
[[params.menu]]
  name = "收藏"
  url = "/favorites"
