baseURL = 'https://everything.cafe/'
languageCode = 'zh-CN'
title = 'Everything and Coffee'
theme = 'deepseek-style-202509292341'

[params]
  name = "陈小明"
  bio = "咖啡 | 空手道 | 旅行达人"
  avatar = "https://avatars.githubusercontent.com/u/7008563"
  stats = [
    { value = 0, label = "动态" },
    { value = 0, label = "关注" },
    { value = 0, label = "粉丝" }
  ]
  socials = [
    { icon = "fab fa-weibo", url = "#" },
    { icon = "fab fa-weixin", url = "#" },
    { icon = "fab fa-github", url = "#" },
    { icon = "fab fa-instagram", url = "#" }
  ]

[[params.menu]]
  name = "动态"
  url = "/"
[[params.menu]]
  name = "文章"
  url = "/posts"
[[params.menu]]
  name = "照片"
  url = "/photos"
[[params.menu]]
  name = "收藏"
  url = "/favorites"
